### ISSUE TITLE
NGINX Problem: FastCGI sent in stder

### ISSUE THREAD

**Issue by pablopapes** [ger86/symfony-docker#14]
Hi! when you go to localhost , you get **File not found.**

in docker logs
FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: dev.symfony-docker.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"

**Comment by pablopapes** [comment]
Solved, just run inside the php container `chown -R www-data:www-data symfony/`

**Comment by ger86** [comment]
Hi Pablo,

Are you using http://localhost ?

The server in your error is: 'dev.symfony-docker.com'

**Comment by pablopapes** [comment]
yes, but I changed to localhost, it's a permissions problem.
just set 777 on the root folder and solved.
