### ISSUE TITLE
missing symfony files

### ISSUE THREAD

**Issue by MaxMayerYOC** [ger86/symfony-docker#6]
the symfony installation misses the vendor directory.

**Comment by boreales** [comment]
Just do a composer install

**Comment by scruffycoderofficial** [comment]
You must run `docker exec -it symfony-docker_php_1 bash` and the on your Project `root` do your `composer install` as per normal.

**Comment by darius-v** [comment]
I have installed them, they appear in container, but in host machine file system they are still not visible and so PhpStorm shows class not exist, etc.

**Comment by darius-v** [comment]
one guy says it is something set in docker-compose.yml that this happens
